version: "3.7"

services:
  db:
    image: postgres
    # restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: appuser
    ports:
      - 5432:5432

  adminer:
    image: adminer
    # restart: always
    ports:
      - 8080:8080

  # web:
  #   build:
  #     context: ./backend
  #     target: dev
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/src
  #   command: npm start
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     NODE_ENV: development
  #     PSQL_HOST: db
  #     DB_NAME: news_blog
  #     DB_USER: appuser
  #     DB_PASS: secret

volumes:
  db: